### PR TITLE
Adding Dockerfile

### PR DESCRIPTION
**Pull request by stevendlander**
Dockerfile created using:

* Debian Jessie
* GDAL 2.0.1

Possible issues:
* Mongoose emits errors with `node-mongodb-native` driver for mongodb upon startup
* Creating users yields an error, possibly due to above
mongoose

### CODE REVIEW

**Comment by stevendlander** [comment]
This fixes #4

**Comment by geospatialmapmashup** [comment]
Awesome would love to run this from Docker Container

**Comment by geospatialmapmashup** [comment]
Can we have it use a new nodejs version?

**Comment by stevendlander** [comment]
Any version of Node *other than* 0.12 fails to build GDAL and install the other necessary npm modules.

6.9.x *could* potentially work, but it required heavy modification of node package configurations which resulted in a very brittle server environment.  :(

**Comment by danielbarela** [comment]
Awesome, I will check this out and merge it soon.

**Pull request merged**
